
// Introduction to Computational Arts
// Project 3

// Instructions
// Click any mouse button to change the color of the bubbles randomly
// as they float across the canvas
// Note: Only one bubble appears on the canvas at a time

// Declare a PImage variable type name kitten
PImage kitten;

// Declare floating point variables for animating the bubbles
float x = 330;
float y = 500;

// The color notation enables transparency of the bubbles to be set to 5f
// Declare color palette for bubble fill
color[] palette = {0x5fff236d, 0x5f0ed9f4, 0x5ff4d921, 0x5f15d921, 0x5f6a037c, 0x5f12037c};

// Declare color palette for bubble stroke
color[] strokePalette = {0x3f0ed9f4, 0x3fff236d, 0x3f15d921, 0x3ff4d921};

// directionX variable randomizes direction and speed along the x-axis
float directionX = random(-5, 5);

// Setup

void setup() {
  // Screen size: 900 x 675
  size(900, 675);
  
  // Load the image of the kitten
  kitten = loadImage("kitten.jpg");
  
  // Set the initial fill color to the first element in the palette array
  fill(palette[0]);
  
  // Set the initial stroke color to the second element in the strokePalette array
  stroke(strokePalette[1]);
}

// Draw
void draw() {
   
  // Position the image of the kitten at position 0, 0 
  image(kitten, 0, 0);
  
  // Draw an ellipse sized 50 x 50 at position x, y
  ellipse(x, y, 50, 50);
  
  // Move the ellipse according to the random number generated by directionX  
  x += directionX;
  // Move the ellipse up on the y axis
  y -= 1;
    
  // If bubbles go beyond the boundaries of the canvas
  if (x > (width + 25) || y > (height + 25) || x < -25 || y < 0) {
    // reset x and y to ther original values
    x = 330;
    y = 500;
    // generate new random number assigned to directionX
    directionX = random(-5, 5);
  }
}

// When any mouse button is clicked
void mouseClicked() {
  // Generate random number to select element from color palettes array
  float fillRandom = random(6);
  float strokeRandom = random(4);
  
  // Change the fill and stroke colors randomly and set strokeWeight to 3
  fill(palette[int(fillRandom)]);
  
  strokeWeight(3);
  stroke(strokePalette[int(strokeRandom)]);
}




