
//Entitled" A Simple Task Which Turned Out To Be Very involved"
//Project 1
//Generated By: Derek Gryga On 30 January 2012
println("Official Property of Derek Gryga");
println("This Is How To Open A Notebook");
println("//This program assumes that the notebook is already in a position on a table or flat surface, waiting to be opened.");
println("1:[Function 1: Reach Notebook]");
println("2:  -Extend Left Shoulder Joint (n*).");//n* is n number of degrees in a circle, where the shoulder and attached arm will rotate to "get" the Left Hand into a grasping position.
println("3:  -Rotate Left Elbow Joint (n*).");//n* is the number of degress necessary for rating the elbow to get the hand into position.
println("4:  -If Left Hand is in position (x,y,z), then execute next function.");
println("5:[Function 2: Open Notebook]");
println("6:  -Rotate Left Wrist to move hand into grasping position.");
println("7:  -Activate Fingers 0-4.");//Fingers 0-4 are the five fingers o nthe left hand, where Finger_0 is the pinky, and Finger_0 is the thumb.
println("8:  -Position Fingers 0-4 into coordinates (x,y,z) to Open Notebook.");//(x,y,z) are the positions the fingers will take to prepare to open the notebook.
println("9:  -Listen for Analog Touch Input from Sensors 0-4");//This si the sense of touch humans have to determine (non-visually) if the notebook cover is in fact, the notebook cover.
println("10:  -If Pressure > than n lb/sq. inch on Analog Touch Input from Sensors 0-4, NoteBook Cover has been detected.");//At a certain point, the cover of the notebook will feel "harder" then the paper, though not as hard as the table or surface.  If it gives, the correct or too much pressure was exerted, and the cover should have been "felt".
println("11: -Rotate Fingers 0-4 (n*) to open around Notebook Cover.");//"Opens" the Left Hand.
println("12: -Rotate Fingers 0-4 (n*) to close around Notebook Cover.");//"Closes" the left hand.
println("13: -If Distance (d) is present between Finger_1 and Finger_2 and Finger_3, then Rotate Left Wrist (n*).");// There will be a minute gap between the2nd and 3rd Fingers and the Thumb, which, unless it is air, should be the notebook cover.
println("14: -End Task");//Take a guess.
