

Ocean ocean;

int WIDTH = 500;
int HEIGHT = 500;

Plankton[] planktons;
int N_PLANKTONS = 300;
int LEFT_PLANKTONS=N_PLANKTONS;
float MAX_PLANKTON_SIZE = 5;
float MAX_PLANKTON_ENERGY = 2;

Prey[] preys;
int N_PREYS =50;//N_PLANKTONS/10;
int LEFT_PREYS=N_PREYS;
float MIN_PREY_SIZE=5;
float MAX_PREY_SIZE = 15;
float MAX_PREY_ENERGY = 3;

Predator[] predators;
int N_PREDATORS=5;
float MIN_PREDATOR_SIZE=8;
float MAX_PREDATOR_SIZE=10;
float MAX_PREDATOR_ENERGY=3;
float MIN_PREDATOR_VERTICES=3;
float MAX_PREDATOR_VERTICES=6;
float MAX_PREDATOR_INHOMO=20;
float MAX_PREDATOR_LEG_LENGTH=3;
float MAX_PREDATOR_POWER=0.1;
float LEG_DEVIDE=8;

float TIDE_X = 0.5;
float TIDE_Y = 0.2;










