
int gato =40;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
gato = gato-2;
rect(gato,gato,gato,gato);
