
PFont font1;
//array to draw string values to the greyscale range
String words = "AAHS AALS ABAS ABBE ABED ABET ABOS ABRI ABUT ABYE ACTA ACYL ADIT ADOS ADZE AEON AERY AGAR AGAS AGEE AGER AGHA AGIN AGIO AGLY AGMA AGOG AGON AGUE AIDE AILS AINS AIRN AIRT AITS AJEE AKEE ALAE ALAR ALBS ALEE ALEF ALGA ALIF ALIT ALKY ALLS ALLY ALMA ALME ALMS ALOW ALTO ALTS ALUM AMAH AMAS AMBO AMIA AMID AMIN AMIS AMOK AMUS ANAS ANES ANGA ANIL ANIS ANKH ANOA ANSA ANTA APER APOD APSE ARAK ARBS ARCO ARES ARFS ARIA ARIL ARUM ARVO ARYL ASPS ATES ATMA AUKS AVER AVES AVOS AVOW AWEE AWES AWLS AWNS AWNY AWRY AXAL AXIL AYAH AYES AYIN AZAN AZON BAAL BAAS BABU BADE BAFF BAHT BALS BAMS BANE BANI BARM BATT BAUD BAWD BEAU BEDU BELS BEMA BENE BERG BERM BEYS BHUT BIBB BICE BIER BILK BIMA BIOS BIRL BIRR BISE BISK BITT BIZE BLAE BLAM BLAT BLAW BLEB BLET BLIN BOAS BOCK BODE BOLA BOLE BOLO BOOR BORA BORT BOSK BOTA BOTT BOYO BRAE BRAW BREE BREN BRIG BRIN BRIO BRIS BROO BUBO BUBS BUHL BUHR BUMF BUND BUNN BUNT BURA BURD BURG BUSS BYRE BYRL CACA CADE CADI CAFF CAID CAIN CALK CALO CALX CAPH CAPO CARD CARK CARN CARR CASA CATE CAUL CAVY CAWS CAYS CECA CEDE CEDI CEES CEIL CELS CEPE CEPS CERE CERO CESS CETE CHAD CHAM CHAO CHAW CHAY CHIA CHID CHIS CHIT CHON CINE CION CIRE CLOD CLON CLOY COCA CODA CODS COED COFF COFT COHO COIF COIR COLE COLS COLY COMP CONI CONK CONN CONY COOF COOP COOS COOT COPS CORD CORF CORM COSH COSS COTE COUP COWY COXA COYS CRAW CRIS CRUS CUED CUIF CUKE CULM CURF CURN CURR CURS CUSK CWNS CYMA CYME DACE DADO DAFF DAGO DAHL DAHS DAIS DAKS DALS DANG DAPS DARB DATO DAUB DAUT DAWK DAWT DEES DEET DEFI DEIL DEKE DELF DELS DEME DEMY DERE DERM DEVS DEXY DEYS DHAK DHAL DHOW DIDO DIDY DIEL DING DINK DIOL DIPT DIRL DITA DITE DITS DITZ DJIN DOAT DOBY DOER DOFF DOGE DOGY DOIT DOJO DOLS DOLT DOMS DONA DOPA DOPY DORE DORP DORR DORS DOSS DOST DOTH DOTY DOUM DOUR DOUX DOWS DOXY DRAY DREE DREK DRIB DUAD DUBS DUCE DUCI DUES DUGS DUIT DULY DUMA DUNS DUNT DUOS DUPE DUPS DURA DURE DURN DURO DURR DYAD DYER DYNE EATH EAUX EAVE EBON ECHE ECRU ECUS EDDO EDDY EDHS EFFS EFTS EGAD EGAL EGER EGIS EIDE EKED EKES ELAN ELDS ELHI ELLS EMES EMEU EMFS EMIC EMIR EMUS EMYD ENGS ENOL ENOW EONS EPEE EPHA EPOS ERAS ERGO ERGS ERNE ERNS EWER EXES EXPO EYAS EYEN EYER EYNE EYRA EYRE EYRY FADO FALX FANO FARD FARL FASH FAUN FAVA FAWN FAYS FEAL FECK FEDS FEHS FEME FEMS FEOD FERE FERN FESS FETS FEUS FIAR FIBS FICE FICO FIDS FIEF FILO FINK FINO FINS FIRN FISC FIXT FLAY FLEY FLIC FLOE FLUB FLUE FLUS FOCI FOGY FOHN FOIN FONS FOPS FORA FORB FOSS FOYS FOZY FRAE FRAG FRAP FRIT FRIZ FROE FRUG FUBS FUCI FUDS FUGS FUGU FUNS FURL FUTZ FYCE FYKE GABS GABY GADI GADS GAED GAEN GAES GALL GALS GAMA GAMB GAMP GAMS GAMY GANE GAOL GAPY GARB GARS GAST GATS GAUD GAUM GAUN GAUR GECK GEDS GEED GEES GEEZ GELD GELT GENS GENU GEST GETA GEUM GHAT GHIS GIBE GIBS GIDS GIED GIEN GIES GILD GILT GINK GIPS GIRD GIRN GIRT GIST GLEG GLEY GLIA GLIM GLOB GLOM GLOP GOOF GOOP GOOS GORP GORY GOWD GOWK GOYS GRAT GREE GRIG GRUE GRUM GUAN GUAR GUCK GUDE GUID GUVS GYBE GYPS GYRE GYRI GYVE HAAF HAAR HABU HADE HADJ HAED HAEM HAEN HAES HAET HAFT HAHS HAIK HAJI HAJJ HALM HAME HANT HAPS HART HASP HAST HATH HAUT HAWS HEBE HEFT HEHS HEIL HELO HEME HENT HERL HERM HERN HEST HETH HETS HEWN HICK HIED HIES HILA HILI HINS HISN HIST HOAR HODS HOED HOER HOKE HOLK HOLM HOLP HOMY HONG HONS HORA HOVE HOWE HOWF HOWK HOYA HOYS HUCK HUED HUIC HULA HUNH HUNS HWAN HYLA HYPS HYTE IAMB IBEX ICHS IDEM IDES IDYL IKAT ILEA ILEX ILIA ILKA ILKS ILLY IMAM IMID IMMY IMPI INBY INIA INLY INRO INTI IRED IRES ISBA IWIS IXIA IZAR JAGG JAMB JAPE JARL JATO JAUK JAUP JAYS JEED JEES JEEZ JEFE JEHU JELL JEON JETE JEUX JIAO JIMP JINN JINS JOES JOLE JOTA JOUK JOWS JUBA JUBE JUGA JUJU JURA KAAS KABS KADI KAES KAFS KAGU KAIF KAIL KAIN KAKA KAME KAMI KANA KAON KAPA KAPH KARN KATA KATS KAVA KAYO KAYS KBAR KEAS KECK KEEF KEEK KEEL KEET KELP KENO KEPI KEPS KERF KERN KETO KHAF KHAN KHET KHIS KIBE KIEF KIFS KIKE KINA KINE KINO KIRN KIRS KIST KITH KIVA KNAR KNOP KNUR KOAN KOAS KOBO KOBS KOEL KOHL KOLA KOLO KONK KOPH KOPS KORE KORS KOSS KOTO KUDO KUDU KUES KURU KVAS KYAK KYAR KYAT LACS LADE LAIC LAIN LAKH LAKY LALL LAMS LANG LARI LARS LASE LATH LATI LATS LAUD LEAL LEAS LECH LEES LEET LEHR LEIS LEKE LEKS LEKU LENO LEUD LEVA LEVO LEYS LIBS LICH LIEF LIEN LIER LIMN LING LINN LINS LIRE LIRI LITU LOAM LOBO LOCA LOCO LODE LOGE LOGY LOLL LOOF LORE LORN LORY LOTA LOTH LOTI LOUP LOUR LOWE LOWN LUAU LUCE LUES LUFF LUMS LUNA LUNE LUNK LUNT LUNY LUTE LUTZ LUVS LWEI LYES LYRE LYSE MAAR MABE MACH MACS MADS MAES MAGE MAIR MAKO MALM MANA MANO MARC MARL MAUD MAUN MAUT MAWN MAWS MAYS MEED MELL MELS MEMS MENO MEOU MERE MERK MERL MESA METE MEWL MHOS MIBS MICA MIDS MIEN MIGG MIGS MILT MINA MIRI MIRK MIRS MIRY MISE MITY MIXT MOAS MOCS MODI MOIL MOKE MOLA MOLL MOLS MOME MOMI MONS MONY MOOL MOOS MOOT MORA MORS MORT MOTS MOTT MOUE MOXA MOZO MUGG MUMM MUMU MUNI MUNS MUON MURA MURE MURR MYNA NABE NADA NAGS NAIF NAOI NAOS NARC NARD NARY NAVE NAYS NEAP NEBS NEEM NEIF NEMA NENE NETT NEUK NEUM NEVE NEVI NIDE NIDI NILS NIMS NIPA NISI NITE NIXE NIXY NOCK NODI NOES NOGG NOGS NOIL NOLO NOMA NOME NOMS NONA NORI NOTA NOUS NOWS NURD NURL OAST OBES OBIA OBIS OBIT OBOL OCAS ODEA ODIC ODYL OGAM OGEE OGLE OHED OHIA OKAS OKEH OKES OLEA OLEO OLES OLIO OLLA OMER ONYX OOTS OPAH OPED OPES ORAD ORBY ORCA ORCS ORDO ORES ORLE ORRA ORTS ORYX ORZO OSAR OSES OSSA OTIC OTTO OUDS OUPH OWSE OXID OYER OYES OYEZ PACA PACS PADI PAIK PAIL PALL PALP PALY PAMS PARA PARD PARR PASE PATY PAWL PEAG PEAN PECH PEDS PEEN PEHS PEIN PEKE PELE PELF PEON PEPS PESO PEWS PFUI PHIS PHIZ PHON PHOT PHUT PIAL PIAN PIAS PICA PICE PIKA PIKI PILI PILY PIMA PINA PINY PION PIPY PIRN PISO PITA PLAT PLED PLEW PLIE PLOW POCK POCO POGY POIS POLS POME PONE PONS POOD POWS PRAO PRAT PRAU PREE PREX PRIG PROA PROW PSIS PUCK PUJA PULA PULE PULI PULS PUNA PUPA PURI PURL PUTZ PYAS PYES PYIC PYIN PYRE QAID QATS QOPH QUAG QUIN QUOD RADS RAFF RAGA RAGI RAIA RAJA RAKI RALE RAMI RAND RANI RAPT RASE RATO RAYA RAZE RAZZ REBS RECK RECS REDD REDE REDO REES REFT REIF REIN REIS REMS REND REPO REPP RESH RETE RETS RHEA RHOS RHUS RIAL RIAS RIEL RILL RIME RIMY RINS RITE RIVE ROAN ROCS ROIL ROMS ROOD ROPY ROTE ROTL ROTO TOUE ROUP ROUX RUBE RUDD RUED RUER RUES RUGA RULY RUNE RUSE RYAS RYKE RYND RYOT SABE SABS SACS SADE SADI SAGO SAGY SAIN SAKI SALL SALP SALS SAMP SARD SARK SASS SATE SATI SAUL SCAD SCAG SCAT SCOP SCOW SCRY SCUP SCUT SEEL SEER SEGO SEGS SEIF SEIS SELS SEME SENE SEPT SERA SERE SERF SERS SETA SETT SEXT SHAD SHAH SHAY SHEW SHIV SHMO SHOD SHOG SHRI SHUL SIAL SIBB SIBS SICE SICS SIKE SILD SIMA SIMP SIMS SINH SIPE SIRS SITH SIZY SKAS SKEE SKEG SKEP SKIT SHUA SLAW SLEW SLUB SLUE SMEW SMIT SNAW SNED SNIB SNIT SNYE SOJA SOKE SOLA SOLI SOLS SOMA SONE SOOK SOPH SOPS SORA SORB SORI SOTH SOUK SOUS SOYS SPAE SPEC SPRY SPUE SRIS STAW STET STEY STOA STOB STUM SUBA SUDD SUER SUES SUGH SULU SUNN SUPE SUQS SURA SURD SUSS SYBO SYCE SYKE SYLI SYNE SYPH TABU TACE TACH TACT TADS TAEL TAHR TAIN TAKA TALA TALI TAMP TAMS TANG TAOS TAPA TARN TASS TAUS TAVS TAWS TAXA TEED TEEL TEEM TEFF TEGS TELA TELS TEPA TERN TETH TETS TEWS THAE THEW THIO THIR THOU THRO THRU TIPI TIRL TIRO TITI TIVY TODS TODY TOEA TOED TOFT TOIT TOLA TOLE TOLU TOME TOMS TONG TOPE TOPH TOPI TORA TORC TORI TORO TORR TORS TORT TOST TOWY TOYO TREF TRET TREY TRIG TROP TRUG TSKS TUFA TUFF TUIS TULE TUMP TUNG TUNS TUPS TWAE TWAS TYEE TYER TYES TYPP TYPY TYRO UDOS UGHS ULAN ULNA ULUS ULVA UNBO UMPS UNAI UNAU UNBE UNCI UNCO UNDE UPAS UPBY URBS URDS URIC URSA URUS UVEA UTAS VAGI VAIR VANG VARA VARS VASA VATU VAUS VAVS VAWS VEEP VEES VELA VELD VENA VIAL VIGA VIGS VILL VIMS VINA VINY VIOL VIRL VISE VITA VROW VUGG VUGH VUGS WABS WADI WADY WAES WAFF WAIL WAIN WAIR WALE WALY WAME WANS WANY WAPS WARK WAST WATS WAUK WAUL WAUR WAWL WAWS WEAL WEAN WEEL WEEN WEER WEES WEET WEFT WEIR WEKA WEND WENS WERT WHAP WHEE WHEW WHID WHIG WHIN WHIR WHIT WHIZ WHOA WHYS WICH WILE WILY WINY WIRY WISS WITE WOAD WONS WOPS WOST WOTS WOVE WUSS WYCH WYES WYLE WYND WYNN WYNS WYTE XYST YACK YAFF YAGI YALD YANG YARE YAUD YAUP YAWL YAWP YAWS YAYS YEAN YEAS YECH YEGG YELK YENS YERK YETT YEWS YILL YINS YIPE YIRD YIRR YLEM YOCK YODH YODS YOGH YOKS YOND YONI YOWE YOWL YOWS YUAN YUCA YUCH YUGA YUKS YUPS YURT YWIS ZARF ZEBU ZEDS ZEES ZEIN ZEKS ZERK ZETA ZILL ZING ZINS ZITI ZOEA ZOIC ZOON ZORI ZYME";
String[] split_words = split(words, ' ');
int current_word;
int i = 0;
int j;

void setup() {

  size(500, 400);
  smooth();
  frameRate(1);
}

void draw() {

  background(0);
  font1 = loadFont("AvenirLTStd-Medium-65.vlw");
  textFont(font1, 65);

  //i = (i + 1) % split_words.length; 
  //j = i - 1;

  current_word = i;//(j) % split_words.length;
  float word_width = textWidth(split_words[current_word]);

  //char[] split_characters = split(split_words[current_word]);
  for (int k = 0; k < split_words[current_word].length(); k++) {
    colour_letter(split_words[current_word], k);

    float x = (width/2.0f) - (word_width/2.0f);

    for (int l = 0; l < k; l++) {
      x+=5;
      x+=textWidth(split_words[current_word].charAt(l));
    }
    //textAlign(CENTER);  
    text("" + split_words[current_word].charAt(k), x, height/2);
  }
  //fill(200);
  i++;
  if (i > words.length()) {
    i=0;
  }

  //textAlign(CENTER);
  //text("" + split_words[current_word],width/2,height/2);
}


void colour_letter(String alphabet, int i) {
  switch(alphabet.charAt(i)) {
  case 'A':
    fill(247, 236, 45);
    break;
  case 'B':
    fill(247, 236, 45);
    break;
  case 'C':
    fill(204, 220, 44);
    break;
  case 'D':
    fill(165, 206, 57);
    break;
  case 'E':
    fill(131, 196, 65);
    break;
  case 'F':
    fill(114, 191, 68);
    break;
  case 'G':
    fill(110, 190, 68);
    break;
  case 'H':
    fill(114, 192, 84);
    break;
  case 'I':
    fill(114, 196, 139);
    break;
  case 'J':
    fill(114, 201, 189);
    break;
  case 'K':
    fill(105, 204, 227);
    break;
  case 'L':
    fill(69, 183, 233);
    break;
  case 'M':
    fill(71, 124, 191);
    break;
  case 'N':
    fill(247, 142, 33);
    break;  
  case 'O':
    fill(241, 90, 34);
    break;
  case 'P':
    fill(238, 47, 38);
    break;
  case 'Q':
    fill(238, 37, 67);
    break;
  case 'R':
    fill(237, 36, 117);
    break;  
  case 'S':
    fill(233, 59, 149);
    break;  
  case 'T':
    fill(200, 78, 157);
    break;
  case 'U':
    fill(171, 82, 159);
    break;
  case 'V':
    fill(137, 82, 161);
    break;
  case 'W':
    fill(106, 83, 163);
    break;
  case 'X':
    fill(80, 84, 164);
    break;
  case 'Y':
    fill(61, 84, 165);
    break;
  case 'Z':
    fill(66, 95, 172);
    break;

  default:
    break;
  }
}


