
size(640, 360);

background(255,140,0);
strokeJoin(BEVEL);
stroke(0);
int s= 100;
fill(204,50,153);
ellipse(330,260,s+800,s+800);
fill(238,130,238);
ellipse(330,260,s+700,s+700);
fill(136,31,120);
noStroke();
ellipse(330,260,s+600,s+600);
fill(0,255,0);
ellipse(330,260,s+500,s+500);
stroke(0);
fill(102,205,0);
ellipse(330,260,s+400,s+400);
fill(69,139,0);
ellipse(330,260,s+300,s+300);
fill(0,128,0);
ellipse(330,260,s+200,s+200);
fill(0,100,0);
ellipse(330,260,s + 100,s+100);
fill(0,250,0);
ellipse(330,260,s,s);

//bkgDOTS
int a = 10;
int b = 20;
int c = 30;
int d = 40;
int e = 50;
int f = 60;
int g = 70;
int h = 80;
int i = 90;
int j = 100;
int k = 110;
int l = 120;
int m = 130;
int n = 140;
int o = 150;
int p = 160;
int q = 170;
int r = 180;
int ss = 190;
int t = 200;
int u = 210;
int v = 220;
int w = 230;
int xx= 240;
int yy= 250;
int zz= 260;
int ab= 270;
int ac= 280;
int ad= 290;
int ae= 300;
int af= 310;
int ag= 320;
int ah= 330;
int ai= 340;
int aj= 350;
int ak= 360;



fill(255,255,255,255);
noStroke();
ellipse(a,a,a,a);
ellipse(a,b,a,a);
ellipse(a,c,a,a);
ellipse(a,d,a,a);
ellipse(a,e,a,a);
ellipse(a,f,a,a);
ellipse(a,g,a,a);
ellipse(a,h,a,a);
ellipse(a,i,a,a);
ellipse(a,j,a,a);
ellipse(a,k,a,a);
ellipse(a,l,a,a);
ellipse(a,m,a,a);
ellipse(a,n,a,a);
ellipse(a,o,a,a);
ellipse(a,p,a,a);
ellipse(a,q,a,a);
ellipse(a,r,a,a);
ellipse(a,ss,a,a);
ellipse(a,t,a,a);
ellipse(a,u,a,a);
ellipse(a,v,a,a);
ellipse(a,w,a,a);
ellipse(a,xx,a,a);
ellipse(a,yy,a,a);
ellipse(a,zz,a,a);
ellipse(a,ab,a,a);
ellipse(a,ac,a,a);
ellipse(a,ad,a,a);
ellipse(a,ae,a,a);
ellipse(a,af,a,a);
ellipse(a,ag,a,a);
ellipse(a,ah,a,a);
ellipse(a,ai,a,a);
ellipse(a,aj,a,a);
ellipse(a,ak,a,a);

fill(255,255,255,235);
ellipse(b,a,a,a);
ellipse(b,b,a,a);
ellipse(b,c,a,a);
ellipse(b,d,a,a);
ellipse(b,e,a,a);
ellipse(b,f,a,a);
ellipse(b,g,a,a);
ellipse(b,h,a,a);
ellipse(b,i,a,a);
ellipse(b,j,a,a);
ellipse(b,k,a,a);
ellipse(b,l,a,a);
ellipse(b,m,a,a);
ellipse(b,n,a,a);
ellipse(b,o,a,a);
ellipse(b,p,a,a);
ellipse(b,q,a,a);
ellipse(b,r,a,a);
ellipse(b,ss,a,a);
ellipse(b,t,a,a);
ellipse(b,u,a,a);
ellipse(b,v,a,a);
ellipse(b,w,a,a);
ellipse(b,xx,a,a);
ellipse(b,yy,a,a);
ellipse(b,zz,a,a);
ellipse(b,ab,a,a);
ellipse(b,ac,a,a);
ellipse(b,ad,a,a);
ellipse(b,ae,a,a);
ellipse(b,af,a,a);
ellipse(b,ag,a,a);
ellipse(b,ah,a,a);
ellipse(b,ai,a,a);
ellipse(b,aj,a,a);
ellipse(b,ak,a,a);

fill(255,255,255,215);
ellipse(c,a,a,a);
ellipse(c,b,a,a);
ellipse(c,c,a,a);
ellipse(c,d,a,a);
ellipse(c,e,a,a);
ellipse(c,f,a,a);
ellipse(c,g,a,a);
ellipse(c,h,a,a);
ellipse(c,i,a,a);
ellipse(c,j,a,a);
ellipse(c,k,a,a);
ellipse(c,l,a,a);
ellipse(c,m,a,a);
ellipse(c,n,a,a);
ellipse(c,o,a,a);
ellipse(c,p,a,a);
ellipse(c,q,a,a);
ellipse(c,r,a,a);
ellipse(c,ss,a,a);
ellipse(c,t,a,a);
ellipse(c,u,a,a);
ellipse(c,v,a,a);
ellipse(c,w,a,a);
ellipse(c,xx,a,a);
ellipse(c,yy,a,a);
ellipse(c,zz,a,a);
ellipse(c,ab,a,a);
ellipse(c,ac,a,a);
ellipse(c,ad,a,a);
ellipse(c,ae,a,a);
ellipse(c,af,a,a);
ellipse(c,ag,a,a);
ellipse(c,ah,a,a);
ellipse(c,ai,a,a);
ellipse(c,aj,a,a);
ellipse(c,ak,a,a);

fill(255,255,255,195);
ellipse(d,a,a,a);
ellipse(d,b,a,a);
ellipse(d,c,a,a);
ellipse(d,d,a,a);
ellipse(d,e,a,a);
ellipse(d,f,a,a);
ellipse(d,g,a,a);
ellipse(d,h,a,a);
ellipse(d,i,a,a);
ellipse(d,j,a,a);
ellipse(d,k,a,a);
ellipse(d,l,a,a);
ellipse(d,m,a,a);
ellipse(d,n,a,a);
ellipse(d,o,a,a);
ellipse(d,p,a,a);
ellipse(d,q,a,a);
ellipse(d,r,a,a);
ellipse(d,ss,a,a);
ellipse(d,t,a,a);
ellipse(d,u,a,a);
ellipse(d,v,a,a);
ellipse(d,w,a,a);
ellipse(d,xx,a,a);
ellipse(d,yy,a,a);
ellipse(d,zz,a,a);
ellipse(d,ab,a,a);
ellipse(d,ac,a,a);
ellipse(d,ad,a,a);
ellipse(d,ae,a,a);
ellipse(d,af,a,a);
ellipse(d,ag,a,a);
ellipse(d,ah,a,a);
ellipse(d,ai,a,a);
ellipse(d,aj,a,a);
ellipse(d,ak,a,a);

fill(255,255,255,175);
ellipse(e,a,a,a);
ellipse(e,b,a,a);
ellipse(e,c,a,a);
ellipse(e,d,a,a);
ellipse(e,e,a,a);
ellipse(e,f,a,a);
ellipse(e,g,a,a);
ellipse(e,h,a,a);
ellipse(e,i,a,a);
ellipse(e,j,a,a);
ellipse(e,k,a,a);
ellipse(e,l,a,a);
ellipse(e,m,a,a);
ellipse(e,n,a,a);
ellipse(e,o,a,a);
ellipse(e,p,a,a);
ellipse(e,q,a,a);
ellipse(e,r,a,a);
ellipse(e,ss,a,a);
ellipse(e,t,a,a);
ellipse(e,u,a,a);
ellipse(e,v,a,a);
ellipse(e,w,a,a);
ellipse(e,xx,a,a);
ellipse(e,yy,a,a);
ellipse(e,zz,a,a);
ellipse(e,ab,a,a);
ellipse(e,ac,a,a);
ellipse(e,ad,a,a);
ellipse(e,ae,a,a);
ellipse(e,af,a,a);
ellipse(e,ag,a,a);
ellipse(e,ah,a,a);
ellipse(e,ai,a,a);
ellipse(e,aj,a,a);
ellipse(e,ak,a,a);

fill(255,255,255,155);
ellipse(f,a,a,a);
ellipse(f,b,a,a);
ellipse(f,c,a,a);
ellipse(f,d,a,a);
ellipse(f,e,a,a);
ellipse(f,f,a,a);
ellipse(f,g,a,a);
ellipse(f,h,a,a);
ellipse(f,i,a,a);
ellipse(f,j,a,a);
ellipse(f,k,a,a);
ellipse(f,l,a,a);
ellipse(f,m,a,a);
ellipse(f,n,a,a);
ellipse(f,o,a,a);
ellipse(f,p,a,a);
ellipse(f,q,a,a);
ellipse(f,r,a,a);
ellipse(f,ss,a,a);
ellipse(f,t,a,a);
ellipse(f,u,a,a);
ellipse(f,v,a,a);
ellipse(f,w,a,a);
ellipse(f,xx,a,a);
ellipse(f,yy,a,a);
ellipse(f,zz,a,a);
ellipse(f,ab,a,a);
ellipse(f,ac,a,a);
ellipse(f,ad,a,a);
ellipse(f,ae,a,a);
ellipse(f,af,a,a);
ellipse(f,ag,a,a);
ellipse(f,ah,a,a);
ellipse(f,ai,a,a);
ellipse(f,aj,a,a);
ellipse(f,ak,a,a);

fill(255,255,255,135);
ellipse(g,a,a,a);
ellipse(g,b,a,a);
ellipse(g,c,a,a);
ellipse(g,d,a,a);
ellipse(g,e,a,a);
ellipse(g,f,a,a);
ellipse(g,g,a,a);
ellipse(g,h,a,a);
ellipse(g,i,a,a);
ellipse(g,j,a,a);
ellipse(g,k,a,a);
ellipse(g,l,a,a);
ellipse(g,m,a,a);
ellipse(g,n,a,a);
ellipse(g,o,a,a);
ellipse(g,p,a,a);
ellipse(g,q,a,a);
ellipse(g,r,a,a);
ellipse(g,ss,a,a);
ellipse(g,t,a,a);
ellipse(g,u,a,a);
ellipse(g,v,a,a);
ellipse(g,w,a,a);
ellipse(g,xx,a,a);
ellipse(g,yy,a,a);
ellipse(g,zz,a,a);
ellipse(g,ab,a,a);
ellipse(g,ac,a,a);
ellipse(g,ad,a,a);
ellipse(g,ae,a,a);
ellipse(g,af,a,a);
ellipse(g,ag,a,a);
ellipse(g,ah,a,a);
ellipse(g,ai,a,a);
ellipse(g,aj,a,a);
ellipse(g,ak,a,a);

fill(255,255,255,115);
ellipse(h,a,a,a);
ellipse(h,b,a,a);
ellipse(h,c,a,a);
ellipse(h,d,a,a);
ellipse(h,e,a,a);
ellipse(h,f,a,a);
ellipse(h,g,a,a);
ellipse(h,h,a,a);
ellipse(h,i,a,a);
ellipse(h,j,a,a);
ellipse(h,k,a,a);
ellipse(h,l,a,a);
ellipse(h,m,a,a);
ellipse(h,n,a,a);
ellipse(h,o,a,a);
ellipse(h,p,a,a);
ellipse(h,q,a,a);
ellipse(h,r,a,a);
ellipse(h,ss,a,a);
ellipse(h,t,a,a);
ellipse(h,u,a,a);
ellipse(h,v,a,a);
ellipse(h,w,a,a);
ellipse(h,xx,a,a);
ellipse(h,yy,a,a);
ellipse(h,zz,a,a);
ellipse(h,ab,a,a);
ellipse(h,ac,a,a);
ellipse(h,ad,a,a);
ellipse(h,ae,a,a);
ellipse(h,af,a,a);
ellipse(h,ag,a,a);
ellipse(h,ah,a,a);
ellipse(h,ai,a,a);
ellipse(h,aj,a,a);
ellipse(h,ak,a,a);

fill(255,255,255,95);
ellipse(i,a,a,a);
ellipse(i,b,a,a);
ellipse(i,c,a,a);
ellipse(i,d,a,a);
ellipse(i,e,a,a);
ellipse(i,f,a,a);
ellipse(i,g,a,a);
ellipse(i,h,a,a);
ellipse(i,i,a,a);
ellipse(i,j,a,a);
ellipse(i,k,a,a);
ellipse(i,l,a,a);
ellipse(i,m,a,a);
ellipse(i,n,a,a);
ellipse(i,o,a,a);
ellipse(i,p,a,a);
ellipse(i,q,a,a);
ellipse(i,r,a,a);
ellipse(i,ss,a,a);
ellipse(i,t,a,a);
ellipse(i,u,a,a);
ellipse(i,v,a,a);
ellipse(i,w,a,a);
ellipse(i,xx,a,a);
ellipse(i,yy,a,a);
ellipse(i,zz,a,a);
ellipse(i,ab,a,a);
ellipse(i,ac,a,a);
ellipse(i,ad,a,a);
ellipse(i,ae,a,a);
ellipse(i,af,a,a);
ellipse(i,ag,a,a);
ellipse(i,ah,a,a);
ellipse(i,ai,a,a);
ellipse(i,aj,a,a);
ellipse(i,ak,a,a);

fill(255,255,255,75);
ellipse(j,a,a,a);
ellipse(j,b,a,a);
ellipse(j,c,a,a);
ellipse(j,d,a,a);
ellipse(j,e,a,a);
ellipse(j,f,a,a);
ellipse(j,g,a,a);
ellipse(j,h,a,a);
ellipse(j,i,a,a);
ellipse(j,j,a,a);
ellipse(j,k,a,a);
ellipse(j,l,a,a);
ellipse(j,m,a,a);
ellipse(j,n,a,a);
ellipse(j,o,a,a);
ellipse(j,p,a,a);
ellipse(j,q,a,a);
ellipse(j,r,a,a);
ellipse(j,ss,a,a);
ellipse(j,t,a,a);
ellipse(j,u,a,a);
ellipse(j,v,a,a);
ellipse(j,w,a,a);
ellipse(j,xx,a,a);
ellipse(j,yy,a,a);
ellipse(j,zz,a,a);
ellipse(j,ab,a,a);
ellipse(j,ac,a,a);
ellipse(j,ad,a,a);
ellipse(j,ae,a,a);
ellipse(j,af,a,a);
ellipse(j,ag,a,a);
ellipse(j,ah,a,a);
ellipse(j,ai,a,a);
ellipse(j,aj,a,a);
ellipse(j,ak,a,a);

fill(255,255,255,55);
ellipse(k,a,a,a);
ellipse(k,b,a,a);
ellipse(k,c,a,a);
ellipse(k,d,a,a);
ellipse(k,e,a,a);
ellipse(k,f,a,a);
ellipse(k,g,a,a);
ellipse(k,h,a,a);
ellipse(k,i,a,a);
ellipse(k,j,a,a);
ellipse(k,k,a,a);
ellipse(k,l,a,a);
ellipse(k,m,a,a);
ellipse(k,n,a,a);
ellipse(k,o,a,a);
ellipse(k,p,a,a);
ellipse(k,q,a,a);
ellipse(k,r,a,a);
ellipse(k,ss,a,a);
ellipse(k,t,a,a);
ellipse(k,u,a,a);
ellipse(k,v,a,a);
ellipse(k,w,a,a);
ellipse(k,xx,a,a);
ellipse(k,yy,a,a);
ellipse(k,zz,a,a);
ellipse(k,ab,a,a);
ellipse(k,ac,a,a);
ellipse(k,ad,a,a);
ellipse(k,ae,a,a);
ellipse(k,af,a,a);
ellipse(k,ag,a,a);
ellipse(k,ah,a,a);
ellipse(k,ai,a,a);
ellipse(k,aj,a,a);
ellipse(k,ak,a,a);

fill(255,255,255,35);
ellipse(l,a,a,a);
ellipse(l,b,a,a);
ellipse(l,c,a,a);
ellipse(l,d,a,a);
ellipse(l,e,a,a);
ellipse(l,f,a,a);
ellipse(l,g,a,a);
ellipse(l,h,a,a);
ellipse(l,i,a,a);
ellipse(l,j,a,a);
ellipse(l,k,a,a);
ellipse(l,l,a,a);
ellipse(l,m,a,a);
ellipse(l,n,a,a);
ellipse(l,o,a,a);
ellipse(l,p,a,a);
ellipse(l,q,a,a);
ellipse(l,r,a,a);
ellipse(l,ss,a,a);
ellipse(l,t,a,a);
ellipse(l,u,a,a);
ellipse(l,v,a,a);
ellipse(l,w,a,a);
ellipse(l,xx,a,a);
ellipse(l,yy,a,a);
ellipse(l,zz,a,a);
ellipse(l,ab,a,a);
ellipse(l,ac,a,a);
ellipse(l,ad,a,a);
ellipse(l,ae,a,a);
ellipse(l,af,a,a);
ellipse(l,ag,a,a);
ellipse(l,ah,a,a);
ellipse(l,ai,a,a);
ellipse(l,aj,a,a);
ellipse(l,ak,a,a);

fill(255,255,255,15);
ellipse(m,a,a,a);
ellipse(m,b,a,a);
ellipse(m,c,a,a);
ellipse(m,d,a,a);
ellipse(m,e,a,a);
ellipse(m,f,a,a);
ellipse(m,g,a,a);
ellipse(m,h,a,a);
ellipse(m,i,a,a);
ellipse(m,j,a,a);
ellipse(m,k,a,a);
ellipse(m,l,a,a);
ellipse(m,m,a,a);
ellipse(m,n,a,a);
ellipse(m,o,a,a);
ellipse(m,p,a,a);
ellipse(m,q,a,a);
ellipse(m,r,a,a);
ellipse(m,ss,a,a);
ellipse(m,t,a,a);
ellipse(m,u,a,a);
ellipse(m,v,a,a);
ellipse(m,w,a,a);
ellipse(m,xx,a,a);
ellipse(m,yy,a,a);
ellipse(m,zz,a,a);
ellipse(m,ab,a,a);
ellipse(m,ac,a,a);
ellipse(m,ad,a,a);
ellipse(m,ae,a,a);
ellipse(m,af,a,a);
ellipse(m,ag,a,a);
ellipse(m,ah,a,a);
ellipse(m,ai,a,a);
ellipse(m,aj,a,a);
ellipse(m,ak,a,a);

// floorDotted
//fill(7,255,0,100);
//stroke(1,100,81);
//for(int y =0; y<= height; y +=8) {
  //for (int x=-0; x <=width; x+=15) {
    //ellipse(x+y,y,16-y/10.0,16-y/10.0);
//  }
//}
//school house

stroke(0);strokeWeight(2);
//school house outline
fill(200);
rect(125, 160, 205, 100);
//roof
beginShape();
vertex(125,160);
vertex(125,130);
vertex(230,100);
vertex(330,130);
vertex(330,160);
endShape();

//side
fill(155);
rect(45,160, 80, 100);
//sideroof
rect(45,130, 80, 30);
quad(125,100,45,130,125,130,230,100);

//front door 
fill(0);
rect(215, 210, 30, 50);
stroke(200);
line(230,210, 230,260);


//windows
int dd = 16;
int kk = 170;
rect(130,kk,dd,dd);
rect(160,kk,dd,dd);
rect(190,kk,dd,dd);
rect(220,kk,dd,dd);
rect(250,kk,dd,dd);
rect(280,kk,dd,dd);
rect(310,kk,dd,dd);
rect(130, kk+20,dd,dd);
rect(160,kk+20,dd,dd);
rect(190,kk+20,dd,dd);
rect(220,kk+20,dd,dd);
rect(250,kk+20,dd,dd);
rect(280,kk+20,dd,dd);
rect(310,kk+20,dd,dd);
//roof with lines INSTEAD OF custom shape
//line(45,160,65,115);
//line(65, 115, 105, 115);
//line(123, 160, 105, 115);
//line(320, 115, 345, 160);
//line( 320, 115, 105, 115);

//pathway
fill(135,31,120);
noStroke();
quad(244,260,215,260,600,400,640,280);


//stars
fill(235,244,41);
stroke(240,200,20);
beginShape();
vertex(445,46);
vertex(456,60);
vertex(475,60);
vertex(464,69);
vertex(467,85);
vertex(452,78);
vertex(444,93);
vertex(444,76);
vertex(426,74);
vertex(443,63);
vertex(445,46);
endShape(CLOSE);


beginShape();
vertex(324+20,77);
vertex(331+20,96);
vertex(348+20,101);
vertex(332+20,109);
vertex(328+20,128);
vertex(319+20,111);
vertex(304+20,115);
vertex(311+20,102);
vertex(301+20,91);
vertex(318+20,93);
vertex(324+20,77);
endShape(CLOSE);
