
println("How to Fold a Paper Crane");
println("Start with a square sheet of paper. The front of your paper should be the side you want to show in the end, or side A,");
println("Fold the paper in half, into a rectangle.");
println("Crease fold crisply");
println("Unfold, and fold in half the other way.");
println("Unfold your rectangle. Turn the paper over and fold in half into a triangle. You should see the back of your paper. Unfold and repeat along the other diagonal.");
println("Unfold your paper and turn it back over. You should see the diagonal creases create 'valleys' and the perpendicular creases create 'mountains'.");
println("Bring the corners together. Allow the valley creases to meet in the middle.");
println("Align the square. By flattening two opposite sides you should find yourself with a square that is open on the bottom. Make sure your square is rotated so that the opening is on the bottom.");
println("Bring the right corner of the top flap to the middle crease, so that the lower right edge lines up with the crease.");
println("Repeat this action on the left, so that the top looks like a kite.");
println("Fold down the top corner to make the crease lie along the horizontal line created in the previous two steps.");
println("Unfold. In doing so, you return to having a square with an opening facing down.");
println("Take the bottom corner of the square and start to fold it up along the horizontal crease you made in the previous two steps.");
println("As you fold, note the four diagonal creases on the inside that you made earlier. You will need to reverse the two creases on the upper flap. To reverse a crease, fold it in the opposite direction that it naturally folds.");
println("Bring the outer edges to the middle and flatten, so that you have a diamond.");
println("Turn your paper over, and repeat the previous five steps.");
println("Fold the edges to the middle crease.");
println("Repeat on the other side.");
println("Fold the right flap over to the left (in the same manner as turning the page of a book). Turn over and repeat on the back.");
println("Take the bottom tip of the top flap and fold it up to the top corner. Turn over and repeat on the other side.");
println("Fold the right flap over to the left (in the same manner as turning the page of a book). Turn over and repeat on the back. Now the head and tail are nestled in between what will become the wings.");
println("Fold the wings down so that they are perpendicular to the body, head and tail.");
println("Fold the tip of the head down.");
println("Pull the head and tail out so that they line up with the outer edges of the body.");
println("Create 3D volume. If you want a three dimensional body, you can grasp the opposite corners on the bottom of the body and gently pull to create the desired volume.");
println("Give away, hang, string, or simply enjoy!");
