
//Generated by Derek Gryga
//Generated on 11 March 2013
//"Wonderful Red Wheels"









































//








































Doughnut[] DoughnutArray = new Doughnut [333];
void setup() {
  size(1000, 500);
  println("This is a game.  In order to win the game, you need to figure out exactly how many Red Wheels are on the screen.");
  println("There are four buttons to press on the keyboard, numbers 1-4, which may help.  If the buttons do not help, there is another solution to find out how many Red Wheels there are, but you have to find it.");
  for (int doughnutNumber = 0; doughnutNumber < 333; doughnutNumber = doughnutNumber + 1) {
    DoughnutArray[doughnutNumber] = new Doughnut();
    DoughnutArray[doughnutNumber].PosX = int(random(width));
  }
};
void draw() {
  background(0);
  for (int doughnutNumber = 0; doughnutNumber < 333; doughnutNumber = doughnutNumber + 1) {
    DoughnutArray[doughnutNumber].DISPLAY();
    DoughnutArray[doughnutNumber].moveDoughnutmove();
    DoughnutArray[doughnutNumber].colorswitch();
  }
};
void keyPressed() {
  if (key == '1') {
    println("NullDefectReturned: Value =1. Multiply returned value by 0.");
  }
  if (key == '2') {
    println("Zero_Dynamic_Tables_Accessed: Table_Value = 2.Press2 Again. Then press 3, three times.");
  }
  if (key == '3') {
    println("AuthorizationCode '3' Required: Code ERROR. Check syntax for HINT_ERRORS.");
  }
  if (key == '4') {
    println("Unexpected_Token: Error Code;4.  Multiply returned value by 0.");
  }
} 
  class Doughnut {

    //Attributes
    int   doughnutSize;
    int   doughnutHoleSize;
    color doughnutColor;
    color doughnutHoleColor;
    color doughnutHoleColor2;
    color doughnutHoleColor3;
    int PosX;
    int PosY;
    float doughnutspeed;
    //Constructor Statement
    Doughnut() {
      doughnutSize      = 200;
      doughnutHoleSize  = 100;
      doughnutColor     = color(255, 54, 23);
      doughnutHoleColor = color(0);
      doughnutHoleColor2= color(55,227,44);
      doughnutHoleColor3= color(167,9,3);
      PosX              = 250;
      PosY              = 250;
    }
    void DISPLAY() {
      fill   (doughnutColor);   
      ellipse(PosX, PosY, doughnutSize, doughnutSize);
      fill   (doughnutHoleColor3);
      fill   (doughnutHoleColor2);
      fill   (doughnutHoleColor);
      ellipse(PosX, PosY, doughnutHoleSize, doughnutHoleSize);
    }
    void moveDoughnutmove() {
      if (PosX > width) {
        PosX = 0;
      }
      if (PosX >= 0) {
        PosX = PosX + 100;
      }
      if (PosY >= 900) {
        PosY = 0;
      }
    }
    void colorswitch()  {
      if (key == '3') {
      fill(doughnutHoleColor2);
    }
      if (key == '4') {
      color(doughnutHoleColor3);
      }    
  }
  }
  //Psst.  Over here! Hint: There are 333 Red Wheels.

