
size(700,850);
background(0);
stroke(250);
noFill();
//x du cercle
  int cercleX;
cercleX = 200;
//y du cercle
int cercleY;
cercleY = 350;
//taille du cercle
int tailleCercle;
tailleCercle = 60;
int TailleCercle; 
TailleCercle = 60;

//motif qui se voit sous 4 facettes
//Première figure haut gauche
//Première facette (bas)
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);

//Deuxième facette
cercleY = cercleY-80;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);

//deuxième figure à droite
//x du cercle
cercleX = 450;
//y du cercle
cercleY = 50;

//première facette
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);


//deuxième facette
cercleY = cercleY+80;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);

// troisième figure bas gauche 
//x du cercle
cercleX = 400;
//y du cercle
cercleY = 860;

//première facette
cercleY = cercleY-80;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);

//deuxième facette
cercleY = cercleY-80;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);

// quatrième figure bas droite 
//x du cercle
cercleX = 200;
//y du cercle
cercleY = 670;

//première facette
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);


//deuxième facette
cercleX = cercleX+20;
cercleY = cercleY-300;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX-10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
cercleY = cercleY+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);
cercleX = cercleX+10;
ellipse(cercleX,cercleY,tailleCercle,TailleCercle);


