
int imageIndex=0;
int numImages=195;
PImage[] myImages=new PImage[numImages];

void setup() {
  size (800, 500);
  background(0);
  frameRate(8);
  imageMode(CENTER);
  myImages[0]= loadImage ("+1.jpg");
  myImages[1]= loadImage ("About.jpg");
  myImages[2]= loadImage ("AddPhoto.jpg");
  myImages[3]= loadImage ("AddToCart.jpg");
  myImages[4]= loadImage ("AddtoCircles.jpg");
  myImages[5]= loadImage ("AmazonMenu.jpg");
  myImages[6]= loadImage ("AppleMenu.jpg");
  myImages[7]= loadImage ("AskQuestion.jpg");
  myImages[8]= loadImage ("BuyNow.jpg");
  myImages[9]= loadImage ("Cancel.jpg");
  myImages[10]= loadImage ("Cart.jpg");
  myImages[11]= loadImage ("Categories.jpg");
  myImages[12]= loadImage ("Comedy.jpg");
  myImages[13]= loadImage ("Comment.jpg");
  myImages[14]= loadImage ("Compose.jpg");
  myImages[15]= loadImage ("Delete.jpg");
  myImages[16]= loadImage ("EditProfile_2.jpg");
  myImages[17]= loadImage ("EditProfile.jpg");
  myImages[18]= loadImage ("Entertainment.jpg");
  myImages[19]= loadImage ("FBMenu.jpg");
  myImages[20]= loadImage ("Film&Ani.jpg");
  myImages[21]= loadImage ("FindUsOnFB.jpg");
  myImages[22]= loadImage ("Follow.jpg");
  myImages[23]= loadImage ("Friends.jpg");
  myImages[24]= loadImage ("Gaming.jpg");
  myImages[25]= loadImage ("GetDirection.jpg");
  myImages[26]= loadImage ("Google+Nav.jpg");
  myImages[27]= loadImage ("Help.jpg");
  myImages[28]= loadImage ("ImOver18.jpg");
  myImages[29]= loadImage ("Info.jpg");
  myImages[30]= loadImage ("Insert.jpg");
  myImages[31]= loadImage ("InviteFriends.jpg");
  myImages[32]= loadImage ("JoinDecline.jpg");
  myImages[33]= loadImage ("LearnMore.jpg");
  myImages[34]= loadImage ("Like.jpg");
  myImages[35]= loadImage ("Login_2.jpg");
  myImages[36]= loadImage ("Login.jpg");
  myImages[37]= loadImage ("Message.jpg");
  myImages[38]= loadImage ("MostViewToday.jpg");
  myImages[39]= loadImage ("MyPlaces.jpg");
  myImages[40]= loadImage ("Navigation.jpg");
  myImages[41]= loadImage ("NewFolder.jpg");
  myImages[42]= loadImage ("NewOpen.jpg");
  myImages[43]= loadImage ("Nonprofits&Act.jpg");
  myImages[44]= loadImage ("Okay.jpg");
  myImages[45]= loadImage ("Open.jpg");
  myImages[46]= loadImage ("People&Blogs.jpg");
  myImages[47]= loadImage ("Person.jpg");
  myImages[48]= loadImage ("Pets&Animals.jpg");
  myImages[49]= loadImage ("Photos.jpg");
  myImages[50]= loadImage ("Print.jpg");
  myImages[51]= loadImage ("RecommendedTopics.jpg");
  myImages[52]= loadImage ("RecordFromWebcam.jpg");
  myImages[53]= loadImage ("Save.jpg");
  myImages[54]= loadImage ("Science&Tech.jpg");
  myImages[55]= loadImage ("Search.jpg");
  myImages[56]= loadImage ("SendMessage.jpg");
  myImages[57]= loadImage ("Settings.jpg");
  myImages[58]= loadImage ("ShowNow.jpg");
  myImages[59]= loadImage ("SignUp.jpg");
  myImages[60]= loadImage ("Sports.jpg");
  myImages[61]= loadImage ("StartaHangout.jpg");
  myImages[62]= loadImage ("StartPosting.jpg");
  myImages[63]= loadImage ("Travel&Events.jpg");
  myImages[64]= loadImage ("TwitterMenu.jpg");
  myImages[65]= loadImage ("Unfollow.jpg");
  myImages[66]= loadImage ("UpdateStatus.jpg");
  myImages[67]= loadImage ("UploadPhotos.jpg");
  myImages[68]= loadImage ("UploadVideo.jpg");
  myImages[69]= loadImage ("ViewMenu.jpg");
  myImages[70]= loadImage ("Wall.jpg");
  myImages[71]= loadImage ("Window.jpg");
  myImages[72]= loadImage ("WishList.jpg");
  myImages[73]= loadImage ("YTMenu.jpg");
  myImages[74]= loadImage ("ABC_2.jpg");
  myImages[75]= loadImage ("ABC.jpg");
  myImages[76]= loadImage ("Add.jpg");
  myImages[77]= loadImage ("AddNew.jpg");
  myImages[78]= loadImage ("AddOption.jpg");
  myImages[79]= loadImage ("AddPage.jpg");
  myImages[80]= loadImage ("AddPhoto_2.jpg");
  myImages[81]= loadImage ("AddProduct.jpg");
  myImages[82]= loadImage ("AddToCart_2.jpg");
  myImages[83]= loadImage ("AddVariety.jpg");
  myImages[84]= loadImage ("AddVideo.jpg");
  myImages[85]= loadImage ("Align_2.jpg");
  myImages[86]= loadImage ("Align.jpg");
  myImages[87]= loadImage ("AlignCenter.jpg");
  myImages[88]= loadImage ("Appearance.jpg");
  myImages[89]= loadImage ("Apply.jpg");
  myImages[90]= loadImage ("Arrow_2.jpg");
  myImages[91]= loadImage ("Arrow_3.jpg");
  myImages[92]= loadImage ("Arrow_4.jpg");
  myImages[93]= loadImage ("Arrow_5.jpg");
  myImages[94]= loadImage ("Arrow_6.jpg");
  myImages[95]= loadImage ("Arrow_7.jpg");
  myImages[96]= loadImage ("Arrow.jpg");
  myImages[97]= loadImage ("AttachmentPostURL.jpg");
  myImages[98]= loadImage ("Bold.jpg");
  myImages[99]= loadImage ("BrokenLink.jpg");
  myImages[100]= loadImage ("Buy.jpg");
  myImages[101]= loadImage ("BuyNow_2.jpg");
  myImages[102]= loadImage ("ChangeDiscussion.jpg");
  myImages[103]= loadImage ("Checkout.jpg");
  myImages[104]= loadImage ("ClickHere.jpg");
  myImages[105]= loadImage ("Collapse.jpg");
  myImages[106]= loadImage ("CollapseMenu.jpg");
  myImages[107]= loadImage ("Comments.jpg");
  myImages[108]= loadImage ("Dashboard.jpg");
  myImages[109]= loadImage ("Edit.jpg");
  myImages[110]= loadImage ("EditImage.jpg");
  myImages[111]= loadImage ("EditOptions.jpg");
  myImages[112]= loadImage ("EnterProject.jpg");
  myImages[113]= loadImage ("Expand_2.jpg");
  myImages[114]= loadImage ("Expand.jpg");
  myImages[115]= loadImage ("Feedbacks.jpg");
  myImages[116]= loadImage ("FileURL.jpg");
  myImages[117]= loadImage ("Filter.jpg");
  myImages[118]= loadImage ("FromComputer.jpg");
  myImages[119]= loadImage ("FromURL_2.jpg");
  myImages[120]= loadImage ("FromURL.jpg");
  myImages[121]= loadImage ("GetFBMobile.jpg");
  myImages[122]= loadImage ("GetShortlink.jpg");
  myImages[123]= loadImage ("Help_2.jpg");
  myImages[124]= loadImage ("Home.jpg");
  myImages[125]= loadImage ("ImStillListening.jpg");
  myImages[126]= loadImage ("InsertIntoPost.jpg");
  myImages[127]= loadImage ("Italic.jpg");
  myImages[128]= loadImage ("Latest.jpg");
  myImages[129]= loadImage ("Link.jpg");
  myImages[130]= loadImage ("Links.jpg");
  myImages[131]= loadImage ("List_2.jpg");
  myImages[132]= loadImage ("List.jpg");
  myImages[133]= loadImage ("Media.jpg");
  myImages[134]= loadImage ("MediaLibrary.jpg");
  myImages[135]= loadImage ("Menu.jpg");
  myImages[136]= loadImage ("Message_2.jpg");
  myImages[137]= loadImage ("MoveToTrash.jpg");
  myImages[138]= loadImage ("MusicFeed.jpg");
  myImages[139]= loadImage ("MyProfile.jpg");
  myImages[140]= loadImage ("NeverForThisSite.jpg");
  myImages[141]= loadImage ("None.jpg");
  myImages[142]= loadImage ("NowPlaying.jpg");
  myImages[143]= loadImage ("OlderPosts.jpg");
  myImages[144]= loadImage ("Options.jpg");
  myImages[145]= loadImage ("Outline.jpg");
  myImages[146]= loadImage ("Pages.jpg");
  myImages[147]= loadImage ("Pause.jpg");
  myImages[148]= loadImage ("Play.jpg");
  myImages[149]= loadImage ("Plus.jpg");
  myImages[150]= loadImage ("Polls.jpg");
  myImages[151]= loadImage ("Posts.jpg");
  myImages[152]= loadImage ("Preview.jpg");
  myImages[153]= loadImage ("PreviewChanges.jpg");
  myImages[154]= loadImage ("Publish_2.jpg");
  myImages[155]= loadImage ("Publish.jpg");
  myImages[156]= loadImage ("Question.jpg");
  myImages[157]= loadImage ("Quotes.jpg");
  myImages[158]= loadImage ("Ratings.jpg");
  myImages[159]= loadImage ("Refresh.jpg");
  myImages[160]= loadImage ("Reset.jpg");
  myImages[161]= loadImage ("SaveAllChanges.jpg");
  myImages[162]= loadImage ("SaveDraft_2.jpg");
  myImages[163]= loadImage ("SaveDraft.jpg");
  myImages[164]= loadImage ("SavePassword.jpg");
  myImages[165]= loadImage ("ScreenOptions.jpg");
  myImages[166]= loadImage ("Search_2.jpg");
  myImages[167]= loadImage ("SearchPosts.jpg");
  myImages[168]= loadImage ("SelectFiles.jpg");
  myImages[169]= loadImage ("Settings_2.jpg");
  myImages[170]= loadImage ("Share.jpg");
  myImages[171]= loadImage ("SignUp_2.jpg");
  myImages[172]= loadImage ("Skip.jpg");
  myImages[173]= loadImage ("Store.jpg");
  myImages[174]= loadImage ("ThumbsDown.jpg");
  myImages[175]= loadImage ("ThumbsUp.jpg");
  myImages[176]= loadImage ("Tools.jpg");
  myImages[177]= loadImage ("TopBlogs.jpg");
  myImages[178]= loadImage ("TopPosts.jpg");
  myImages[179]= loadImage ("Trash.jpg");
  myImages[180]= loadImage ("TurnOn.jpg");
  myImages[181]= loadImage ("Update.jpg");
  myImages[182]= loadImage ("Upgrade_2.jpg");
  myImages[183]= loadImage ("Upgrade.jpg");
  myImages[184]= loadImage ("UpgradeToPro.jpg");
  myImages[185]= loadImage ("Upload.jpg");
  myImages[186]= loadImage ("Users.jpg");
  myImages[187]= loadImage ("View_2.jpg");
  myImages[188]= loadImage ("View_3.jpg");
  myImages[189]= loadImage ("View.jpg");
  myImages[190]= loadImage ("ViewAs.jpg");
  myImages[191]= loadImage ("ViewPost.jpg");
  myImages[192]= loadImage ("VisitTheChrome.jpg");
  myImages[193]= loadImage ("Zoom_2.jpg");
  myImages[194]= loadImage ("Zoom.jpg");
  
  
}

void draw() {
  background(0);
  if (mousePressed) {
    if (dist(mouseX, mouseY, width/2, height/2) < 20)
    imageIndex = (int) random(numImages);
  }
   int i = imageIndex%195;
  if (myImages[i]!=null) {
    image(myImages[i], 400, 240);
  } else {
    println("Image" + i + "is reporting null, Double check this image exists.");
  }
}





