
print("Still I Rise");
println();
println();
println("You may write me down in history");
println("With your bitter, twisted lies");
println("You may trod me in the very dirt");
println("But still, like dust, I'll rise.");
println();
println();
println("Does my sassiness upset you?");
println("Why are you beset with gloom?");
println("'Cause I walk like I've got oil wells");
println("Pumping in my living room.");
println();
println();
println("Just like moons and like suns,");
println("With the certainty of tides.");
println("Just like hopes springing high");
println("Still I'll rise.");
