
size (900,900);
int centerx=width/2;
int centery=height/2;
background (110,50,80);
noStroke ();
int triangle_scale=1000;
int ax=centerx;
int bx=centerx-triangle_scale;
int cx=centerx+triangle_scale;
int ay=centery-triangle_scale;
int by=centery+triangle_scale;
int cy=by;
fill (100,75,90);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=900;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (100,60,90);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=850;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (90,50,80);

triangle (ax,ay,bx,by,cx,cy);
triangle_scale=800;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (100,50,80);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=750;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (90,40,70);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=700;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (100,40,70);

triangle (ax,ay,bx,by,cx,cy);
triangle_scale=650;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (90,30,60);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=600;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (80,20,50);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=550;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (70,10,40);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=500;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (70,20,10);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=450;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (60,10,0);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=400;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (50,0,40);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=350;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (40,0,30);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=300;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (30,0,20);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=250;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (20,0,10);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=200;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (10,0,0);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=150;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (20,0,10);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=100;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (30,0,20);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=90;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (40,10,30);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=80;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (50,20,40);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=70;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (60,10,0);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=60;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (70,20,10);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=50;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (70,10,40);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=40;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (80,20,50);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=30;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (90,30,60);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=20;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (100,40,70);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=10;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (110,50,80);
triangle (ax,ay,bx,by,cx,cy);
triangle_scale=10;
ax=centerx;
bx=centerx-triangle_scale;
cx=centerx+triangle_scale;
ay=centery-triangle_scale;
by=centery+triangle_scale;
cy=by;
fill (0);




