
//code generated by Jack Choi

float x=20;
PImage bg;
//void setup
void setup(){ 
  size(700,467);
    bg = loadImage("light.jpg");
  smooth();
  noStroke();
  frameRate(3);
}

void draw(){
      background(bg);
  // making random
  for (int i = 0; i < 30; i++) {
  float r = random(-20, 20);
  //background, blurring and opacity

  x = x+30;
  translate(0,100); 
  rotate(x);
  fill(120+i,100+r,50);//orange
  ellipse(r,r,5+i,5+i);
   fill(0,0,150+i,20);//blue
  ellipse(10+r,10+r,7+r,7+r);
   fill(0,100+r,0,60);//green
 ellipse(4/r,+r,r,r);
  fill(100+i,0,0,100);//red
 ellipse(90+r,2*r,r+i,r+i);
 
  
  }
}


