
// Geometrical Geometrical spiral curves generated by the mouse coordinates.
// Hue of the color generated by mouse coordinates, too.
// Abstract curved shapes in rich specter of colors
// Keyboard Input: DELETE or BACKSPACE for start screen
// Keyboard Input: S or S for save screen shot 

PImage photo1;
PImage photo2;
PImage photo3;
PImage photo4;
float k;


void setup(){
  size(800, 800);
  photo1 = loadImage("1.jpg");  
  photo2 = loadImage("9.jpg");
  photo3 = loadImage("12.jpg");  
  photo4 = loadImage("16.jpg");
  colorMode(HSB, 360, 100, 100, 100);
  smooth();
  noFill();
  background(0);
}

color s1 = color(HSB,360, 100, 100);
float g = 0;
float m = 0;

void draw(){
  
  if(mousePressed){
    s1 = color(360-int((mouseX+mouseY)/4.444), int(random(50, 100)), int(random(40, 100)), 100);
    image(photo1, mouseX, 0, 100, 100);
    image(photo2, 0, mouseY, 100, 100);
    image(photo3, mouseX, 700, 100, 100);
    image(photo4, 700, mouseY, 100, 100);
    pushMatrix();
    beginShape();
    for (g=0; g<400; g=g+20){
      float x1 = mouseX + g * cos(m);
      float y1 = mouseY + g * sin(m);
      stroke(s1);
      strokeWeight(0.01);
      vertex(x1, y1);
      m += 10;
    }
    endShape();
    popMatrix();
  }
}

void keyReleased(){
  if (key == DELETE || key == BACKSPACE) background(0);
  if (key=='s' || key=='S') saveFrame();
 }

