
// Need G4P library
import g4p_controls.*;


public void setup(){
  size(480, 320, JAVA2D);
  createGUI();
  customGUI();
  // Place your setup code here
  
}

public void draw(){
  background(230);
  
}

// Use this method to add additional statements
// to customise the GUI controls
public void customGUI(){

}

float changeToFar(float value) {
  value = (value-32)*5/9;
  return value;
}
 
float changeToCel(float value) {
  value = value*9/5+32;
  return value;
}

/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void F2C_clicked1(GOption source, GEvent event) { //_CODE_:F2C:853167:
//  println("F2C - GOption event occured " + System.currentTimeMillis()%10000000 );

  label1.setText("Fahrenheit Value =");
  label1.setTextBold();
  label2.setText(temp_slider1.getValueS());
  label2.setTextBold();
  label3.setText("Celsius Value =");
  label3.setTextBold();
  label4.setText(nfc(changeToFar(temp_slider1.getValueF()),0));
  label4.setTextBold();
} //_CODE_:F2C:853167:

public void C2F_clicked2(GOption source, GEvent event) { //_CODE_:C2F:481933:
//  println("C2F - GOption event occured " + System.currentTimeMillis()%10000000 );

  label1.setText("Celsius Value =");
  label1.setTextBold();
  label2.setText(temp_slider1.getValueS());
  label2.setTextBold();
  label3.setText("Fahrenheit Value =");
  label3.setTextBold();
  label4.setText(nfc(changeToCel(temp_slider1.getValueF()),0));
  label4.setTextBold();

} //_CODE_:C2F:481933:

public void temp_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:temp_slider1:845383:
//  println("temp_slider1 - GCustomSlider event occured " + System.currentTimeMillis()%10000000 );
  
//  label1.setText(temp_slider1);
  if(F2C.isSelected()) {
  label1.setText("Fahrenheit Value =");
  label1.setTextBold();
  label2.setText(temp_slider1.getValueS());
  label2.setTextBold();
  label3.setText("Celsius Value =");
  label3.setTextBold();
  label4.setText(nfc(changeToFar(temp_slider1.getValueF()),0));
  label4.setTextBold();
  }
  else {
  label1.setText("Celsius Value =");
  label1.setTextBold();
  label2.setText(temp_slider1.getValueS());
  label2.setTextBold();
  label3.setText("Fahrenheit Value =");
  label3.setTextBold();
  label4.setText(nfc(changeToCel(temp_slider1.getValueF()),0));
  label4.setTextBold();
  }
  
  
} //_CODE_:temp_slider1:845383:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  togGroup1 = new GToggleGroup();
  F2C = new GOption(this, 20, 20, 152, 32);
  F2C.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  F2C.setText("Fahrenheit to Celsius");
  F2C.setTextBold();
  F2C.setOpaque(false);
  F2C.addEventHandler(this, "F2C_clicked1");
  C2F = new GOption(this, 180, 20, 150, 30);
  C2F.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  C2F.setText("Celsius to Fahrenheit");
  C2F.setTextBold();
  C2F.setOpaque(false);
  C2F.addEventHandler(this, "C2F_clicked2");
  togGroup1.addControl(F2C);
  F2C.setSelected(true);
  togGroup1.addControl(C2F);
  temp_slider1 = new GCustomSlider(this, 20, 80, 380, 100, "grey_blue");
  temp_slider1.setShowValue(true);
  temp_slider1.setShowLimits(true);
  temp_slider1.setLimits(0, 0, 700);
  temp_slider1.setNbrTicks(15);
  temp_slider1.setStickToTicks(true);
  temp_slider1.setShowTicks(true);
  temp_slider1.setNumberFormat(G4P.INTEGER, 0);
  temp_slider1.setOpaque(false);
  temp_slider1.addEventHandler(this, "temp_slider1_change1");
  label1 = new GLabel(this, 20, 200, 150, 20);
  label1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label1.setText("Fahrenheit value =");
  label1.setTextBold();
  label1.setOpaque(true);
  label2 = new GLabel(this, 190, 200, 80, 20);
  label2.setText("0");
  label2.setTextBold();
  label2.setOpaque(false);
  label3 = new GLabel(this, 20, 240, 150, 20);
  label3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label3.setText("Celsius Value =");
  label3.setTextBold();
  label3.setOpaque(false);
  label4 = new GLabel(this, 190, 240, 80, 20);
  label4.setText("-17");
  label4.setTextBold();
  label4.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GToggleGroup togGroup1; 
GOption F2C; 
GOption C2F; 
GCustomSlider temp_slider1; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 



