
// codes generated by Yosub Jack Choi

PImage bg;
size(700,467);
smooth();
bg = loadImage("road2.jpg");
 background(bg);
 
// 
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 60; i += 5){
  noFill();
  stroke(0,100,100,40);
  strokeWeight(1);
  ellipse(j, i + 150, 900, 250);
}
}
 
// 
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 70; i += 5){
  noFill();
   stroke(0,100,200,100);
  strokeWeight(0.75);
  ellipse(j + 50, i +350, 700, 450);
}
}
 
// 
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 80; i += 5){
  noFill();
   stroke(0,200,150,90);
  strokeWeight(0.5);
  ellipse(j + 50, i + 250, 900, 450);
}
}

// 
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 80; i += 5){
  noFill();
   stroke(50,180,200,50);
  strokeWeight(0.75);
  ellipse(j + 50, i + 200, 900, 450);
}
}
 
// 
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 70; i += 5){
  noFill();
  stroke(#98095F,30);
  strokeWeight(5);
  ellipse(j + 50, i + 450, 900, 450);
}
}

//
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 70; i += 5){
  noFill();
  stroke(150,90,30,200);
  strokeWeight(1);
  ellipse(j + 120, i + 470, 900, 450);
}
}
 // 
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 80; i += 5){
  noFill();
   stroke(100,50,150,150);
  strokeWeight(0.5);
  ellipse(i + 80, j + 20, 1500, 800);
}
}
 // 
for(int i =- 10; i < 400; i += 10 ){
for(int j =- 10; i < 80; i += 5){
  noFill();
   stroke(200,180,80,100);
  strokeWeight(0.5);
  ellipse(i + 90, j + 50, 1500, 820);
}
}

