
PFont f;
// The font must be located in the sketch's
// "data" directory to load successfully
PImage img;

String title ="FIRST THINGS FIRST 1964: A MANIFESTO.";
String copy = "WE, THE UNDERSIGNED, ARE GRAPHIC DESIGNERS, PHOTOGRAPHERS AND STUDENTS WHO HAVE BEEN BROUGHT UP IN A WORLD IN WHICH THE TECHNIQUES AND APPARATUS OF ADVERTISING HAVE PERSISTENTLY BEEN PRESENTED TO US AS THE MOST LUCRATIVE, EFFECTIVE AND DESIRABLE MEANS OF USING OUR TALENTS. WE HAVE BEEN BOMBARDED WITH PUBLICATIONS DEVOTED TO THIS BELIEF, APPLAUDING THE WORK OF THOSE WHO HAVE FLOGGED THEIR SKILL AND IMAGINATION TO SELL SUCH THINGS AS: CAT FOOD, STOMACH POWDERS, DETERGENT, HAIR RESTORER, STRIPED TOOTHPASTE, AFTERSHAVE LOTION, BEFORESHAVE LOTION, SLIMMING DIETS, FATTENING DIETS, DEODORANTS, FIZZY WATER, CIGARETTES, ROLL-ONS, PULL-ONS AND SLIP-ONS. BY FAR THE GREATEST EFFORT OF THOSE WORKING IN THE ADVERTISING INDUSTRY ARE WASTED ON THESE TRIVIAL PURPOSES, WHICH CONTRIBUTE LITTLE OR NOTHING TO OUR NATIONAL PROSPERITY. IN COMMON WITH AN INCREASING NUMER OF THE GENERAL PUBLIC, WE HAVE REACHED A SATURATION POINT AT WHICH THE HIGH PITCHED SCREAM OF CONSUMER SELLING IS NO MORE THAN SHEER NOISE. WE THINK THAT THERE ARE OTHER THINGS MORE WORTH USING OUR SKILL AND EXPERIENCE ON. THERE ARE SIGNS FOR STREETS AND BUILDINGS, BOOKS AND PERIODICALS, CATALOGUES, INSTRUCTIONAL MANUALS, INDUSTRIAL PHOTOGRAPHY, EDUCATIONAL AIDS, FILMS, TELEVISION FEATURES, SCIENTIFIC AND INDUSTRIAL PUBLICATIONS AND ALL THE OTHER MEDIA THROUGH WHICH WE PROMOTE OUR TRADE, OUR EDUCATION, OUR CULTURE AND OUR GREATER AWARENESS OF THE WORLD. WE DO NOT ADVOCATE THE ABOLITION OF HIGH PRESSURE CONSUMER ADVERTISING: THIS IS NOT FEASIBLE. NOR DO WE WANT TO TAKE ANY OF THE FUN OUT OF LIFE. BUT WE ARE PROPOSING A REVERSAL OF PRIORITIES IN FAVOUR OF THE MORE USEFUL AND MORE LASTING FORMS OF COMMUNICATION. WE HOPE THAT OUR SOCIETY WILL TIRE OF GIMMICK MERCHANTS, STATUS SALESMEN AND HIDDEN PERSUADERS, AND THAT THE PRIOR CALL ON OUR SKILLS WILL BE FOR WORTHWHILE PURPOSES. WITH THIS IN MIND WE PROPOSE TO SHARE OUR EXPERIENCE AND OPINIONS, AND TO MAKE THEM AVAILABLE TO COLLEAGUES, STUDENTS AND OTHERS WHO MAY BE INTERESTED.";



void setup(){
frameRate(20);
smooth(8);
size(800,800);
f = createFont("Monospaced",22);
  

}

 
 
void draw () {
background(0);
textFont(f, 22);
textAlign(LEFT);

fill(255,0,0);
text(title, 99+random(-.25,.25), 109);
fill(0,255,0);
text(title, 101+random(-.25,.25), 109);
fill(0,0,255);
text(title, 98+random(-.25,.25), 112);
fill(255);
text(title, 100+random(-.125,.125), 110);

textFont(f,10);
textLeading(20);

fill(255,0,0);
text(copy, 100+random(-.125,.125),150,605,1000);
fill(0,255,0);
text(copy, 100+random(-.125,.125),150,605,1000);
fill(0,0,255);
text(copy, 100+random(-.125,.125),150,605,1000);
fill(255);
text(copy, 100+random(-.125,.125),150,605,1000);

}



