
// practicing patterning bezier curves

size(800,600);
background(241,240,225);

fill(207,109,105,60);
stroke(11,12,60,25);
int a = 12;
int b = 24;

bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 2;
b *= 2;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 2;
b *= 2;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 2;
b *= 2;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 2;
b *= 2;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 2;
b *= 2;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 0.5;
b *= 0.5;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 0.5;
b *= 0.5;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 0.5;
b *= 0.5;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 0.5;
b *= 0.5;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);
a *= 0.5;
b *= 0.5;
bezier(a,b,width*0.25,0,width*0.75,height,width-a,height-b);
line(a,b,width-a,height-b);

float x = width*0.5;
float y = height*0.5;

stroke(207,109,105);
strokeWeight(2);
fill(11,12,60,20);

bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);
x += 30;
y += 40;
bezier(0,height,x,y,width-x,height-y,width,0);

bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);
x += 50;
y += 60;
bezier(0,0,x,y,width-x,height-y,width,height);

println("x="+x);
println("y="+y);
println("a="+a);
println("b="+b);


